name: Deploy NameGuard to AWS as a serverless lambda

on:
  push:
    branches:
      - ci-cd-lambda-nameguard-v2
      - main

env:
  NODE_VERSION: '18.16.0'
  TS_VERSION: '4.2.3'
  TS_NODE_VERSION: '10.0.0'

permissions:
  id-token: write
  contents: write

jobs:
  build-image-deploy-serverless:
    runs-on: ubuntu-20.04
    env:
      SERVICE_NAME: nameguard
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email ''

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE}}
          aws-region: us-east-1

      - name: Build and deploy lambda
        run: |
          npm install -g serverless
          npm install serverless-prune-plugin
          serverless deploy --stage prod --param="PROVIDER_URI_GOERLI=${{secrets.PROVIDER_URI_GOERLI}}" --param="PROVIDER_URI_MAINNET=${{secrets.PROVIDER_URI_MAINNET}}" --param="PROVIDER_URI_SEPOLIA=${{secrets.PROVIDER_URI_SEPOLIA}}"
        working-directory: api 

      - name: Delete old images from ECR
        env:
          ECR_REPO: serverless-oss-nameguard-prod
        run: |
          ALL_IMAGES_TO_DELETE=$(aws ecr describe-images --repository-name $ECR_REPO --query 'sort_by(imageDetails,& imagePushedAt)[*].imageDigest' --filter "tagStatus=UNTAGGED" --output json )
          len=`echo $ALL_IMAGES_TO_DELETE | jq length`
          IMAGES_TO_DELETE=$(aws ecr describe-images --repository-name $ECR_REPO --query 'sort_by(imageDetails,& imagePushedAt)[*].imageDigest' --filter "tagStatus=UNTAGGED" --output json | jq '.[0]')
          if [[ $len > 5 ]]; then aws ecr batch-delete-image --repository-name $ECR_REPO --image-ids imageDigest=$IMAGES_TO_DELETE; fi

        working-directory: api

  notify:
    name: Send Slack deployment event notification
    if: ${{ needs.build-image-deploy-serverless.result != 'skipped' && always() }}
    needs: [build-image-deploy-serverless]
    runs-on: ubuntu-20.04
    steps:
      - name: Output status on deployment success
        if: ${{ needs.build-image-deploy-serverless.result == 'success'}}
        run: |
          echo "STATUS=Success  :rocket:" >> $GITHUB_ENV
          echo "TEXT=Lambda nameguard deployed succesfully! :white_check_mark:" >> $GITHUB_ENV

      - name: Output status on deployment failed
        if: ${{ needs.build-image-deploy-serverless.result == 'failure' }}
        run: |
          echo "STATUS=Failure  :x:" >> $GITHUB_ENV
          echo "TEXT=Lambda nameguard deployed failed! :rotating_light:" >> $GITHUB_ENV

      - name: Deployment status Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,workflow,repo
          custom_payload: |
            {
              attachments: [{
                color: '${{ needs.build-image-deploy-serverless.result  }}' === 'success' ? 'good' : '${{ needs.build-image-deploy-serverless.result }}' === 'failure' ? 'danger' : 'warning',
                title: 'Lambda Nameguard deployment.',
                text: '${{ env.TEXT }}',
                fields: [
                {
                  title: 'Repository',
                  value: `${process.env.AS_REPO}`,
                  short: true
                },
                {
                  title: 'Status',
                  value: '${{ env.STATUS }}',
                  short: true
                },
                {
                  title: 'Workflow',
                  value: `${process.env.AS_WORKFLOW}`,
                  short: true
                }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}